### ISSUE TITLE
Install python 3.6

### ISSUE THREAD

**Issue by nickswebsite** [kurron/ansible-role-python-developer#1]
For Ubuntu <= 16.04 you have to add a ppa:

    sudo add-apt-repository ppa:fkrull/deadsnakes
    sudo apt-get update
    sudo apt-get install python3.6

For Ubuntu >= 16.10, it is already in the repos so you just need:

    sudo apt-get install python3.6

**Comment by kurron** [comment]
@nickswebsite  I've followed the instructions and the installation is clean but `python3 --version` still gives me `Python 3.5.2`.  Any suggestions?

**Comment by kurron** [comment]
@nickswebsite  I just ran `/usr/bin/python3.6 --version` and it came back with `Python 3.6.1`.  Is that good enough?

**Comment by kurron** [comment]
No complaints so I assume Python is working as desired.
